[package]
name = "lsm303agr"
version = "0.1.0"
authors = ["Diego Barrios Romero <eldruin@gmail.com>"]
repository = "https://github.com/eldruin/lsm303agr-rs"
license = "MIT OR Apache-2.0"
description = "Platform-agnostic Rust driver for the LSM303AGR ultra-compact high-performance eCompass module: ultra-low-power 3D accelerometer and 3D magnetometer."
readme = "README.md"
keywords = ["inertial", "accelerometer", "gyroscope", "imu", "embedded-hal-driver"]
categories = ["embedded", "hardware-support", "no-std"]
homepage = "https://github.com/eldruin/lsm303agr-rs"
documentation = "https://docs.rs/lsm303agr"
edition = "2018"

[badges]
travis-ci = { repository = "eldruin/lsm303agr-rs", branch = "master" }
coveralls = { repository = "eldruin/lsm303agr-rs", branch = "master", service = "github" }

[dependencies]
embedded-hal = "0.2.3"

[dev-dependencies]
linux-embedded-hal = "0.3"
embedded-hal-mock = "0.7"

[profile.release]
lto = true
